#!/bin/bash
#脚本作用：在MAC中挂载可读可写的NTFS存储设备
#作者：郭飞
#版本：v2.0
#最后修改日期：2022-03-29
#建议:将脚本存放到/usr/local/bin中可作为命令执行

mountDir="$HOME/Desktop"

set -e
#得到所有的外部存储
declare -a disks
declare -a curPaths
index=0
OLDIFS=$IFS         #备份原for循环的分隔符
IFS=$'\n'           #将原for循环的分隔符替换为换行
for i in `mount | grep ntfs`; do
	disk=`echo $i | grep -o disk[0-9]s[0-9]`
	curPath=`echo $i | awk '{print $3}'`
	disks[$index]="$disk"
	curPaths[$index]="$curPath"
	let index=index+1
done
IFS="$OLDIFS"       #恢复for循环原来的分隔符
if [ "$index" == "0" ];then
	echo "没有磁盘可供挂载"
	exit 1
fi

#选择需要挂载的磁盘
index=$[index-1]
for i in `seq 0 $index`;do
	echo $i: ${curPaths[$i]}
done
read -p "请选择你要挂载的NTFS设备：" num


#创建挂载点
mkdir -p "$mountDir/NTFS"

#卸载磁盘
sudo umount ${curPaths[$num]}

#挂载为可写模式
sudo mount_ntfs -o rw,nobrowse /dev/${disks[$num]} $mountDir/NTFS
echo "挂载成功！"

